### ISSUE TITLE
Release v1.1.0 on NPM

### ISSUE THREAD

**Issue by ghost** [Alhadis/language-texinfo#1]
Hello,
I'm looking for a syntax highlighting for `*.info` documents, to use in my project.
The feature is provided in this project in the latest v1.1.0 release, however, on NPM there is only the v1.0.0 release.
Please post this new release on NPM, thank you!

**Comment by Alhadis** [comment]
Oh shit, sorry, I completely forgot that I've been mirroring these packages to NPM. 🤔 (They're chiefly for Atom, which uses a [different registry](https://atom.io/packages/)).

I've gone and [published v1.1.0](https://www.npmjs.com/package/language-texinfo/v/1.1.0) on NPM just now, thanks so much for the reminder!
